version: "3.7"
services:
  client:
    # stdin_open: true
    # tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8800 prod
    #env_file:
    # - ./.env